# Generated by Django 3.1.2 on 2020-10-30 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20201014_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='sqm',
            new_name='sqft',
        ),
    ]
