# Generated by Django 3.1.2 on 2020-10-31 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20201031_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
